# -*- coding: utf-8 -*-
"""Compare-Face
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1ghhrxSSNUa1zf5h417g-6G98F79nmrUL
"""

# Import Depedencies
import cv2
import numpy as np
from insightface.app import FaceAnalysis
import matplotlib.pyplot as plt

# Buat Fungsi Similarity
def calculate_similarity(feat1, feat2):
    dot_prod = np.dot(feat1, feat2)
    norm1 = np.linalg.norm(feat1)
    norm2 = np.linalg.norm(feat2)
    return dot_prod / (norm1 * norm2)

# 1. Inisialisasi InsightFace Application
# ctx_id=0 artinya menggunakan GPU pertama. Jika ingin menggunakan CPU, set ctx_id=-1
app = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))

# 2. Load Gambar (Ubah path ini sesuai gambar yang kamu upload di Colab)
img1_path = 'gbr2.jpeg'
img2_path = 'jkw2.jpg'

img1 = cv2.imread(img1_path)
img2 = cv2.imread(img2_path)

# 3. Deteksi Wajah dan Ekstrak Embedding Vektor
faces1 = app.get(img1)
faces2 = app.get(img2)

# 4. Validasi apakah wajah terdeteksi di kedua gambar
if len(faces1) == 0:
    print(f"Error: Tidak ada wajah yang terdeteksi di gambar {img1_path}")
elif len(faces2) == 0:
    print(f"Error: Tidak ada wajah yang terdeteksi di gambar {img2_path}")
else:
    # Ambil wajah pertama yang terdeteksi dari masing-masing gambar
    face1 = faces1[0]
    face2 = faces2[0]

    # Ambil 512-D Embedding Vector
    embedding1 = face1.normed_embedding
    embedding2 = face2.normed_embedding

    # 5. Hitung Skor Kemiripan
    similarity_score = calculate_similarity(embedding1, embedding2)

    # 6. Tampilkan Hasil
    print("\n" + "="*40)
    print(f" RESULT COMPARE FACE ")
    print("="*40)
    print(f"Similarity Score : {similarity_score:.4f}")

    # Threshold standar ArcFace untuk kecocokan orang yang sama biasanya >= 0.45
    threshold = 0.45
    if similarity_score >= threshold:
        print("Status           : MATCH (Orang yang Sama)")
    else:
        print("Status           : NOT MATCH (Orang Berbeda)")
    print("="*40)

    # 7. Visualisasi Gambar di Colab
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    axes[0].imshow(cv2.cvtColor(img1, cv2.COLOR_BGR2RGB))
    axes[0].set_title("Gambar 1")
    axes[0].axis('off')

    axes[1].imshow(cv2.cvtColor(img2, cv2.COLOR_BGR2RGB))
    axes[1].set_title("Gambar 2")
    axes[1].axis('off')

    plt.suptitle(f"Similarity: {similarity_score:.4f}", fontsize=16)
    plt.show()
